### ISSUE TITLE
please cut a proper release

### ISSUE THREAD

**Issue by blshkv** [vulnersCom/api#12]
based on the changelog, there are several releases after 1.4.0. Could you tag it properly so that linux distros would pick it up?

we have received a https://github.com/pentoo/pentoo-overlay/pull/432 request and I really would to  avoid such snapshots as it adds extra load on us.

**Comment by vulnersCom** [comment]
Done

**Comment by blshkv** [comment]
thanks, a tiny bit: would be good if you could avoid the ```Release``` world in future

**Comment by vulnersCom** [comment]
Oh, got it, we will. Sorry. 27.03.2019, 15:26, "Anton Bolshakov" <notifications@github.com>:thanks, a tiny bit: would be good if you could avoid the Release world in future—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or mute the thread.  -- Kirill ErmakovVULNERS.COM Mobile: +7 (903) 595-05-03E-mail: isox@vulners.com
